version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5467:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d blogdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/blogdb
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
